'use client';
import { embedderLabel } from '@/lib/logic/browserQa';
import { Button, Table } from '@/components/ds';
import type { ModelMetadata } from '@/lib/types';
import { ensembleModels, number, percent, record } from './trainingView';

export function ModelRepository({ models, disabled, current, onTrain }: { models: ModelMetadata[]; disabled: boolean; current?: string; onTrain: (id: string) => void }) {
  return <section className="space-y-4" aria-labelledby="model-repository"><div className="flex flex-wrap items-center justify-between gap-2"><h2 id="model-repository" className="ds-t-section">모델 저장소</h2><p className="ds-t-caption">다른 세션이 4단계에서 골라 씁니다</p></div><div className="overflow-x-auto"><Table><thead><tr><th scope="col">모델</th><th scope="col">종류</th><th scope="col">학습한 세션</th><th scope="col">학습 건수</th><th scope="col">등급 정확도</th><th scope="col">임베딩</th><th scope="col">행 동작</th></tr></thead><tbody>{ensembleModels(models).map(model => <tr key={model.modelId} aria-current={current === model.modelId ? 'true' : undefined} className={model.selectable === false ? 'opacity-50' : ''}><th scope="row" className="font-mono break-all">{model.modelId}{current === model.modelId && <span className="ds-t-caption block">현재 모델</span>}</th><td>앙상블 4</td><td>{String(model.bk ?? '—')} · {String(record(model.trainedFrom).version ?? '—')}<div className="ds-t-caption">{String(model.oneLiner ?? '—')}</div></td><td>{number(model.n)?.toLocaleString('ko-KR') ?? '확인 불가'}</td><td>{percent(model.metrics?.grade_accuracy)}<div className="ds-t-caption">검증셋 기준</div></td><td>{embedderLabel(model.embedderName ?? model.embedder)}</td><td>{model.selectable === false ? '다른 임베딩으로 학습된 모델입니다' : <Button size="sm" disabled={disabled || model.trainingData === false} onClick={() => onTrain(model.modelId)}>추가 학습</Button>}{model.trainingData === false && <p className="ds-t-caption">기존 학습셋이 없는 모델입니다.</p>}</td></tr>)}</tbody></Table></div><p className="ds-t-caption">추가 학습은 기존 학습셋과 이 세션의 라벨로 새 모델을 만듭니다.</p></section>;
}
