/* eslint-disable @typescript-eslint/no-explicit-any */
import { beforeEach, expect, it, vi } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
const h = vi.hoisted(() => ({values: [] as any[], cursor: 0, data: null as any, options: null as any, session: {sid:'s',sd:{prep:{derivedRef:'ref'}}} as any, push:vi.fn(), refresh:vi.fn(), history:false}));
vi.mock('react', async original => ({...await original<typeof import('react')>(), useState:(initial:any)=>{const i=h.cursor++;if(!(i in h.values))h.values[i]=typeof initial==='function'?initial():initial;return [h.values[i],(next:any)=>{h.values[i]=typeof next==='function'?next(h.values[i]):next;}];},useRef:(v:any)=>{const i=h.cursor++;return h.values[i]??(h.values[i]={current:v});},useCallback:(f:any)=>f,useEffect:()=>{}}));
vi.mock('next/navigation',()=>({useRouter:()=>({push:h.push}),usePathname:()=>'/pipeline/personas'}));
vi.mock('@/stores/useSessionStore',()=>({useSessionStore:()=>h.session}));
vi.mock('@/components/versions/VersionProvider',()=>({useVersion:()=>({version:'v2',readonly:h.history,meta:{activeVersion:'v3'},session:null})}));
vi.mock('@/components/versions/useStageCompletionRefresh',()=>({useStageCompletionRefresh:vi.fn()}));
vi.mock('@/lib/usePolling',()=>({usePolling:(options:any)=>{h.options=options;return {data:h.data,refresh:h.refresh};}}));
vi.mock('@/lib/api/persona',()=>({getPersonaStatus:vi.fn(),getPersonaCards:vi.fn(),getPersonaMap:vi.fn(),getPersonaTree:vi.fn(),startPersona:vi.fn(),retryPersonaCard:vi.fn()}));
vi.mock('@/lib/api/segment',()=>({getSegmentPersonas:vi.fn().mockResolvedValue({personas:[]})}));
import { PersonaScreen } from './PersonaScreen';
import { VersionRouteBoundary } from '../versions/StageVersion';
import Page from '../../app/pipeline/personas/page';
import { OpportunityMap } from './OpportunityMap';
import { CCMTable } from './CCMTable';
import { ContextTable } from './ContextTable';
import * as api from '@/lib/api/persona';
import { addKnownInsight } from '@/lib/api/known';
vi.mock('@/lib/api/known',()=>({addKnownInsight:vi.fn().mockResolvedValue({id:'known1'})}));
function nodes(n:any):any[]{return !n||typeof n!=='object'?[]:Array.isArray(n)?n.flatMap(nodes):[n,...nodes(n.props?.children)];}
function text(n:any):string{return typeof n==='string'||typeof n==='number'?String(n):Array.isArray(n)?n.map(text).join(''):n?.props?text(n.props.children):'';}
const draw=(readonly=false)=>{h.cursor=0;return PersonaScreen({sid:'s',version:'v2',readonly});};
const button=(tree:any,label:string)=>nodes(tree).find(n=>text(n)===label&&n.props?.onClick);
const point=(id:string,odi:number)=>({context_id:id,persona_id:'P1',cluster_id:'CL0',i:.5,s:.4,odi,zone:'B',star:false,counter:false,shape:'circle',tone:0});
beforeEach(()=>{vi.clearAllMocks();h.history=false;h.values=[];h.cursor=0;h.session={sid:'s',sd:{prep:{derivedRef:'ref'}}};h.data={status:{status:'done',run:'r1',progress:1,personas:[{id:'P1',status:'done'}]},cards:{run:'r1',personas:{P1:{status:'done',card:{persona_name:'확정 이름',cluster_id:'CL0',desire:'확정 Desire',goal:['목표'],metrics:{doc_count:12,author_count:8},contexts:[]}}}},map:{points:[point('C1',1),point('C2',3)],base:{s_line:.5,diag1:[[0,.4],[1,1]],diag2:[[.5,0],[1,1]]}},tree:null,identities:[]};});
it('opens map first, switches both views, and opens the point persona card',()=>{let tree=draw();expect(nodes(tree).some(n=>n.type===OpportunityMap)).toBe(true);button(tree,'Persona 카드').props.onClick();tree=draw();expect(text(tree)).toContain('확정 이름');expect(text(tree)).toContain('근거 12건 · 작성자 8명 · Context 0개');button(tree,'전체 맵').props.onClick();tree=draw();nodes(tree).find(n=>n.type===OpportunityMap).props.onOpenCard('P1','C2');tree=draw();expect(button(tree,'Persona 카드').props['aria-pressed']).toBe(true);expect(nodes(tree).some(n=>n.type===OpportunityMap)).toBe(false);});
it('places the sortable Context table below the map',()=>{const tree=draw();const all=nodes(tree);expect(all.findIndex(n=>n.type===ContextTable)).toBeGreaterThan(all.findIndex(n=>n.type===OpportunityMap));const props=all.find(n=>n.type===ContextTable).props;h.values=[];h.cursor=0;let table=ContextTable(props);expect(renderToStaticMarkup(table).indexOf('C2')).toBeLessThan(renderToStaticMarkup(table).indexOf('C1'));button(table,'기회').props.onClick();h.cursor=0;table=ContextTable(props);expect(renderToStaticMarkup(table).indexOf('C1')).toBeLessThan(renderToStaticMarkup(table).indexOf('C2'));});
it('retries only the failed persona with the current run and version',async()=>{h.data.cards.personas.P1.status='failed';h.data.status.personas[0].status='failed';let tree=draw();button(tree,'Persona 카드').props.onClick();tree=draw();expect(text(tree)).toContain('이 페르소나 카드를 만들지 못했습니다.');await button(tree,'다시 만들기').props.onClick();expect(api.retryPersonaCard).toHaveBeenCalledWith('s','P1',{run:'r1'},'v2');});
it('shows the exact missing-package empty state and evidence navigation',()=>{h.data={...h.data,missing:true};const tree=draw();expect(text(tree)).toContain('근거 탐색을 마친 뒤 페르소나를 만들 수 있습니다.');button(tree,'근거 탐색으로').props.onClick();expect(h.push).toHaveBeenCalledWith('/pipeline/evidence');expect(button(tree,'페르소나 만들기')).toBeUndefined();});
it('keeps legacy sessions on the original page and keys new sessions by version',()=>{expect(Page().type).toBe(PersonaScreen);expect(Page().key).toBe('s:v2');h.session.sd={};expect(Page().type).not.toBe(PersonaScreen);});
it('keeps readonly navigation available while disabling retry',()=>{h.data.cards.personas.P1.status='failed';h.data.status.personas[0].status='failed';let tree=draw(true);button(tree,'Persona 카드').props.onClick();tree=draw(true);expect(button(tree,'다시 만들기').props.disabled).toBe(true);});
it('renders intent warning, null attributes and blocked constraint reasons',()=>{h.data.cards.personas.P1.prescription={blocked:true,constraint:[{constraint:'의료적 효과 표현 금지',verdict:'violates',reason:'효과를 단정함'}]};let tree=draw();button(tree,'Persona 카드').props.onClick();tree=draw();button(tree,'8-B 수렴').props.onClick();expect(text(draw())).toContain('의도 ≠ 행동');button(draw(),'8-C 속성').props.onClick();expect(renderToStaticMarkup(draw())).toContain('근거 부족');button(draw(),'8-D 처방').props.onClick();expect(text(draw())).toContain("사내 제약 '의료적 효과 표현 금지'를 지키는 처방을 만들지 못했습니다.");});

it('loads versioned results and refreshes after partial results instead of caching failure',async()=>{const snapshot=h.data;vi.mocked(api.getPersonaStatus).mockResolvedValue(snapshot.status);vi.mocked(api.getPersonaCards).mockResolvedValue(snapshot.cards);vi.mocked(api.getPersonaMap).mockRejectedValueOnce(new Error('결과 준비 중')).mockResolvedValue(snapshot.map);vi.mocked(api.getPersonaTree).mockResolvedValue({id:'product',size:12});draw();const first=await h.options.fetcher();expect(first.map).toBeNull();const second=await h.options.fetcher();expect(second.map.points).toHaveLength(2);expect(api.getPersonaCards).toHaveBeenCalledWith('s','v2');expect(api.getPersonaMap).toHaveBeenCalledTimes(2);});
it('handles missing package returned by the run endpoint',async()=>{h.data.status={status:'idle',run:null,progress:0,personas:[]};vi.mocked(api.startPersona).mockRejectedValueOnce(new Error('근거 탐색을 마친 뒤 페르소나를 만들 수 있습니다.'));await button(draw(),'페르소나 만들기').props.onClick();expect(text(draw())).toContain('근거 탐색을 마친 뒤 페르소나를 만들 수 있습니다.');});
it('enforces readonly in mutation handlers and keeps a single primary',async()=>{h.data.status.status='idle';const tree=draw(true);expect(nodes(tree).filter(n=>n.props?.variant==='primary')).toHaveLength(1);await button(tree,'페르소나 만들기').props.onClick();expect(api.startPersona).not.toHaveBeenCalled();});

it('allows version-aware Persona screens through the historical route boundary',()=>{h.history=true;expect(VersionRouteBoundary({children:'persona child'})).toBe('persona child');h.session.sd={};expect(VersionRouteBoundary({children:'legacy child'})).not.toBe('legacy child');});
it('shows unverified original quotes and adds their source document to Known Insight',async()=>{h.data.cards.personas.P1.card.contexts=[{context_id:'C1',context_name:'상황',state:{text:'상태',cite:['E1']}}];h.data.cards.personas.P1.trace=[{context_id:'C1',field:'state',evidence_id:'E1',evidence:{doc_id:'doc1',source:'카페',quote:{text:'원문 인용',verified:false,field:'body',start:3,end:8}}}];let tree=draw();button(tree,'Persona 카드').props.onClick();tree=draw();const table=nodes(tree).find(n=>n.type===CCMTable);const cell=table.props.contexts[0].cells.state;expect(renderToStaticMarkup(cell.evidence)).toContain('인용 문장을 원문에서 찾지 못해 추론으로 낮췄습니다.');expect(text(cell.evidence)).toContain('원문 인용');await button(cell.evidence,'Known Insight에 추가').props.onClick();expect(addKnownInsight).toHaveBeenCalledWith('s',{type:'doc',doc_id:'doc1'},'v2');});
